name: "DBSize REST Server"
version: "1.0"
slug: "dbsize_server"
description: "A tiny REST server to expose MariaDB size via HTTP for Home Assistant."
startup: services
boot: auto
host_network: true
options: {}
schema: {}
arch:
  - amd64
  - aarch64
  - armv7
init: false
hassio_api: true
hassio_role: default
privileged: []
